### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by Niko-O** [CasparCG/Framework#1]
The Svt.Caspar project is completely undocumented. It would be very helpful to have at least some basic documentation of the classes and their members.
I'm talking about the XML-documentation in the code like this:

``` C#
    /// <summary>
    /// This class is used to do some stuff and it uses <see cref="SomeOtherClass"/> to do that.
    /// </summary>
    public class CasparDevice { ....
```

**Comment by dotarmin** [comment]
Hi @Niko-O!

A bit late (and before my time in CasparCG team) but I will close your issue and move it to a new repository called [CasparCG/dotnet-framework](https://github.com/CasparCG/dotnet-framework/issues).

Best regards,
Armin
